version: '3.8'

services:
  appelcen:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped