version: '3'

services:
  appelcen:
    build:
      context: https://github.com/LaurEC-24/app.git#main
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - /opt/appelcen/logs:/app/logs
    environment:
      - TZ=Europe/Bucharest
    restart: unless-stopped