version: '3.8'

services:
  appelcen:
    build: .
    container_name: appelcen
    ports:
      - "8501:8501"
    volumes:
      - appelcen_logs:/app/logs
    environment:
      - TZ=Europe/Bucharest
    restart: unless-stopped
    networks:
      - appelcen_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appelcen.rule=Host(`appelcen.local`)"  # Modifică domeniul după necesități

volumes:
  appelcen_logs:
    name: appelcen_logs

networks:
  appelcen_network:
    name: appelcen_network
    driver: bridge
