version: '3'

services:
  appelcen:
    build:
      context: https://github.com/LaurEC-24/app.git#main
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - /opt/appelcen/logs:/app/logs
    environment:
      - TZ=Europe/Bucharest
      - DB_HOST=10.10.8.12
      - DB_PORT=1433
      - DB_NAME=Interventii
      - DB_USER=Laur
      - DB_PASSWORD=Hh1236996321
    restart: unless-stopped